### ISSUE TITLE
Not working on the Google Pixel 4

### ISSUE THREAD

**Issue by airbourn** [VR-25/acc#20]
ACC doesn't seem to be working on the Pixel 4 (eg. doesn't stop charging when it reaches the pause charging level). Also tried the `forceStatusAt100=5` workaround - still nothing. Currently on the stock kernel. 

[acc-logs-flame.tar.zip](https://github.com/VR-25/acc/files/3874478/acc-logs-flame.tar.zip)

**Comment by jpcaldwell30** [comment]
I have the same issue as the user above. I have a pixel 4 XL running the latest version of android 10 and after some testing it seems that none of the switches work which is why we are unable to get the service to do anything. After some digging i think its because the phone has different control files/missing ones so we just need to find one that works as a switch. Any ideas on where to start?

**Comment by Aiakio** [comment]
Also same issue here. Pixel 4 XL.

**Comment by VR-25** [comment]
I found the following new charging switches:
```
/sys/devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:google,bms/power_supply/charger/charge_disable 0 1

/sys/kernel/debug/google_charger/chg_suspend 0 1

/sys/kernel/debug/google_charger/input_suspend 0 1
```
Pro tip: the first can be abbreviated as `charger/charge_disable 0 1` because it matches `.*/power_supply/.*`.

Test command: `acc -t [file] [on] [off]`
  e.g. `acc -t charger/charge_disable 0 1`

Set a working switch with `acc -s chargingSwitch [file [on] [off]`
  `acc -s chargingSwitch charger/charge_disable 0 1`

**Comment by jpcaldwell30** [comment]
Thank you! The first one works for me on the Pixel 4 XL. I haven't tried any of the others but I suspect they will as well. Can we expect this to be included in the next app update? Also, could you add the ability to add a custom switch in the app in the select switch popup?

**Comment by VR-25** [comment]
Yes, the next version will include these changes.

**Comment by airbourn** [comment]
@VR-25 Now working on my Pixel 4 as well after trying the commands above. Thanks a lot!
