### ISSUE TITLE
acc daemon gets killed and does not restart

### ISSUE THREAD

**Issue by ElDavoo** [VR-25/acc#205]
Hi,
I'm trying to let my cubot magic charge only from 13:00 to 20:00.
This device is generally very bad, for example CURRENT_NOW is 0 when unplugged.
I found out that every time acc attempts to enable/disable charging, it gets killed.
The problem is, sometimes it restarts, sometimes it doesn't.
Steps to reproduce
1) Start the daemon
2) Execute `acc -d 30%`
3) Watch how the daemon's PID changes (or it does not come back)

I tried `acc -t`, `acc -t p` and only the switch in the config kind of works (which was the automatically chosen one), the others seem to do nothing.

[acc-logs-CUBOT_MAGIC.zip](https://github.com/VR-25/acc/files/12295020/acc-logs-CUBOT_MAGIC.zip)
Can you figure out what is going on?
Thank you

**Comment by VR-25** [comment]
Hi,
Your config is incorrect.

1. Restore the default config (`acc -sr`);

2. Pick the working charging switch (`acc -s s="/proc/mtk_battery_cmd/current_cmd 0::0 0::1 --"`);

3. Set up the desired schedules:

`acc -s a ": day profile; at 13:00 acc 100`

`acc -s a ": night profile; at 20:00 acc 100 30; accd`

Why?
acc -e and -d stop the daemon, because those are "manual modes", meant to be used on demand. We can't have auto mode (daemon) manual modes running simultaneously.
For your day schedule, `acc 100` is equivalent to pause_capacity=100 resume_capacity=95 (pause_capacity - 5).
For night, `acc 100 30; accd` means, the resume threshold is lowered to 30%. To ensure charging stops right away if capacity > 30, accd is restarted. Since offMid=true by default, accd switches charging off if resume_capacity < capacity <= pause_capacity.

**Comment by ElDavoo** [comment]
Wow, I didn't expect such as a detailed response (complete with commands!)! Thank you so much!
A note about this should be added in the comments of the scheduler section imo.

I won't be able to test (vacation time) so i will assume everything works :)
