### ISSUE TITLE
Magisk default settings for ACC/AccA

### ISSUE THREAD

**Issue by eugenesan** [VR-25/acc#214]
**This not a bug but rather a question and maybe a request to document the situation for new users.**

I just did clean device install with AccA and default Magisk settings ((Zygisk: disabled, MountNamespaceMode: Inherit)) and it didn't work properly.
The daemon appeared to be running bu AccA could not access acc command line (acc: inaccessible).

After altering Magisk settings (Zygisk: Enabled, MountNamespaceMode: Global) and reboot issues solved.

**Comment by VR-25** [comment]
Hm, that's weird...

Even if the system lacks writable /sbin/ to have acc executables in $PATH right after installation, AccA should still work, since it always uses the /dev/acc workaround (all executables linked to /dev/).

Are you able to run /dev/acc under the same conditions (clean AccA install and default Magisk settings)?

**Comment by eugenesan** [comment]
I'll have to check that later.
At least for now if somebody will have similar issue they will find this issue and try my solution.

**Comment by VR-25** [comment]
Looks like it had to do with 509eafa951a9fff33da3c72d1a306ae14ad82bd7 .
