### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by Froggy232** [VR-25/acc#272]
Hi,
There isn't been new stable release since October 2023, is there a reasons to it?
Is it better to use the latest RC version, or is there a reason to postpone the upgrade and stay on the stable version? It seems there is a lot of fix and commits between the latest stable and the latest RC.
Thanks for your module, it's a very important one economically and ecology wise, it makes a huge differences.
Best regards

**Comment by VR-25** [comment]
The next stable release is taking a while due to some major design changes and time constraints.
Shouldn't take much longer, though.
Meanwhile, stick with the latest stable if you don't need anything else introduced recently.
If you decide to try a newer version, you can quickly rollback to the last installation and config, by simply running `acc -b`.

**Comment by VR-25** [comment]
[acc_v2024.12.15-rc_202412150_1754.zip](https://github.com/user-attachments/files/18141282/acc_v2024.12.15-rc_202412150_1754.zip)

**Comment by Froggy232** [comment]
Thanks you a lot, I will try this RC right now and will report issue if there is any.
Thanks again!
