### ISSUE TITLE
ACC misreporting mA, never charges phone

### ISSUE THREAD

**Issue by MaciejGorczyca** [VR-25/acc#35]
Hey.

Created issue on ACCA, turns out it's ACC issue. ([ACCA issue post here](https://github.com/MatteCarra/AccA/issues/96))

Whenever I install ACC, the phone stops charging. The diode stops glowing and the system shows that the cable is connected (I can select transfer files, charge etc), the battery icon shows charging BUT the phone is not charging at all.

acc -i shows not charging as well but it always reports current now 515mA and voltage now ~3.7V. Unplugging USB drops current now to 0 mA.

Switching acc -s s didn't change anything.

I know disabling and enabling power used to work with EngineerMode app bundled with the original ROM but it does not work with ACC.

I'm attaching full logs so you should be able to dig out the issue. Perhaps it's just a matter of simple logic error or wrong sensor read.

[acc-logs-hermes.tar.gz](https://github.com/VR-25/acc/files/4429202/acc-logs-hermes.tar.gz)

More info in linked AccA issue post (if needed).

**Comment by VR-25** [comment]
Hey there!

Let me start by saying that MediaTek devices are weird and troublesome by design.
That's one of the major reasons why acc hasn't received a stable update in the last 6 months.
Results among MTK devices are inconsistent.

Ensure you're always up-to-date.
Install the latest version (just released) and run `acc -t /proc/mtk_battery_cmd/current_cmd 0::0 0::1`.
If the output is positive, run `acc -s s="/proc/mtk_battery_cmd/current_cmd 0::0 0::1"` then test `acc -e` and `acc -d`.

If you have a Telegram account (or don't mind creating one), consider contacting me at https://t.me./vr25xda - so we can sort this out much faster.

Regards

**Comment by saiballo** [comment]
Hi,

When run these instructions:

"Install the latest version (just released) and run acc -t /proc/mtk_battery_cmd/current_cmd 0::0 0::1.
If the output is positive, run acc -s s="/proc/mtk_battery_cmd/current_cmd 0::0 0::1" then test acc -e and acc -d."

I receive false output. what can I do? Indeed I have MediaSucks device :-)

**Comment by VR-25** [comment]
The latest version has a  new charging switch for MTK devices.

**Comment by VR-25** [comment]
What are the outputs of `acc -t` and `acc -t /proc/mtk_battery_cmd/current_cmd 0::0 0::1`?

**Comment by MaciejGorczyca** [comment]
Not sure if you are asking me or the other guy but we were chatting months ago on telegram and resolved the issue for my device (Xiaomi Redmi Note 2). I think we can close it. Completely forgot about it.
